// Code generated by tygo. DO NOT EDIT.

//////////
// source: server.go


//////////
// source: types.go

export interface GuestInput {
  name: string;
  dietary_preference: string;
  alcohol_free: boolean;
  is_primary: boolean;
}
export interface RSVPRequest {
  guests: GuestInput[];
}
export interface CreateInviteRequest {
  name: string;
  min_plus: number /* int */;
  max_plus: number /* int */;
  guest_names: string[];
}
export interface UpdateInviteRequest {
  name: string;
  min_plus: number /* int */;
  max_plus: number /* int */;
  guest_names: string[];
}
export interface LoginRequest {
  password: string;
}
export interface StatusResponse {
  status: string;
}
export interface ErrorResponse {
  error: string;
}
export interface GuestResponse {
  id: number /* int64 */;
  name: string;
  dietary_preference: string;
  alcohol_free: boolean;
  is_primary: boolean;
}
export interface InviteResponse {
  id: string;
  name: string;
  min_plus: number /* int */;
  max_plus: number /* int */;
  submitted: boolean;
}
export interface InviteWithGuestsResponse {
  invite: InviteResponse;
  guests: GuestResponse[];
}
export interface ListInvitesResponse {
  invites: InviteResponse[];
}
